# Generated by Django 3.2 on 2021-05-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_owner_pet_race_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
