# Generated by Django 3.2 on 2021-05-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210502_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='mobile',
        ),
    ]
